# Generated by Django 3.2.25 on 2024-04-02 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 12, 55, 22, 599713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 12, 55, 22, 599713, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='borrowing',
            table='Borrowing',
        ),
    ]
