# Generated by Django 3.2.25 on 2024-04-03 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_auto_20240402_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='renewal_count',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='renewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrowed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 6, 37, 37, 522202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 6, 37, 37, 522202, tzinfo=utc)),
        ),
    ]
