# Generated by Django 3.2.25 on 2024-04-03 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_auto_20240403_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrowed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 7, 10, 5, 117308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 7, 10, 5, 117308, tzinfo=utc)),
        ),
    ]
