# Generated by Django 3.2.25 on 2024-04-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_auto_20240403_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
